
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blogapi_development

test:
  <<: *default
  database: blogapi_test

production:
  <<: *default
  database: blogapi_production
  username: blogapi
  password: <%= ENV['POSTGRES_PASSWORD'] %>


